# Site settings

# Setup
title:               Felipe Monteiro Andrade Araújo
tagline:             'dev'
description:         '• Software Engineer • Designer • Creator of tegjs • Information Technology Lawyer'
url:                 https://devfelipemonteiro.com # the base hostname & protocol for your site, e.g. http://example.com
baseurl:             '' # the subpath of your site, e.g. /blog

# Pagination Settings
paginate: 5
paginate_path: "/blog/page:num/"

# Google Analytics
jekyll_analytics:
  GoogleAnalytics:
    id: UA-62517739-1
    anonymizeIp: true

# About/contact
author:
  name: Felipe Monteiro
  url: https://twitter.com/devfelipemonteiro
  email: devfelipemonteiro@gmail.com

# Pages
blog: '/blog'
background: '/background'
activities: '/activities'
publications: '/publications'
projects: '/projects'
awards: '/awards'
about: '/about'

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-analytics
  - jekyll-seo-tag
